-- Schedule the durable Autopilot watchdog.
-- Each deployed environment should provide a Vault secret named project_url.
-- Fresh/local databases may apply this migration before that secret exists:
-- the cron remains installed but emits no HTTP request until configuration is present.
-- The watchdog token itself is generated by migration 0024.

select cron.schedule(
  'riseklix-autopilot-watchdog',
  '*/2 * * * *',
  $cron$
    with watchdog_config as (
      select
        max(decrypted_secret) filter (where name = 'project_url') as project_url,
        max(decrypted_secret) filter (where name = 'autopilot_watchdog_token') as watchdog_token
      from vault.decrypted_secrets
    )
    select net.http_post(
      url := project_url || '/functions/v1/autopilot-watchdog',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-riseklix-watchdog-token', watchdog_token
      ),
      body := '{}'::jsonb,
      timeout_milliseconds := 10000
    ) as request_id
    from watchdog_config
    where project_url is not null
      and watchdog_token is not null;
  $cron$
);
