-- Schedule the durable Autopilot watchdog.
-- Each environment must provide a Vault secret named project_url.
-- The watchdog token itself is generated by migration 0024.

do $$
begin
  if not exists (
    select 1 from vault.decrypted_secrets where name = 'project_url'
  ) then
    raise exception 'Vault secret project_url is required before scheduling the Autopilot watchdog';
  end if;
end
$$;

select cron.schedule(
  'riseklix-autopilot-watchdog',
  '*/2 * * * *',
  $cron$
    select net.http_post(
      url := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url')
             || '/functions/v1/autopilot-watchdog',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-riseklix-watchdog-token',
        (select decrypted_secret from vault.decrypted_secrets where name = 'autopilot_watchdog_token')
      ),
      body := '{}'::jsonb,
      timeout_milliseconds := 10000
    ) as request_id;
  $cron$
);

