import Link from 'next/link'

export default function PrivacyPage() {
  return (
    <main className="legal-shell">
      <article className="legal-document">
        <Link href="/" className="wordmark brand-wordmark" aria-label="Riseklix"><span className="brand-mark" aria-hidden="true" /><strong>RISEKLIX</strong></Link>
        <div className="eyebrow">PRIVACY POLICY · SEPTEMBER 18, 2026</div>
        <h1>Privacy Policy</h1>
        <p className="legal-intro">This policy describes the information Riseklix processes to provide Commercial Discovery workspaces and AI-assisted research.</p>

        <h2>1. Information you provide</h2>
        <p>We process account information such as your name, email address and organization name, plus the company URLs, project settings, corrections, uploaded information and implementation inputs you choose to provide.</p>

        <h2>2. Information generated by the product</h2>
        <p>Riseklix stores research sources, company profiles, Buyer Situations, benchmark questions, model observations, citations, findings, implementation blueprints, workflow states and audit records so that research remains inspectable and can be rechecked over time.</p>

        <h2>3. Authentication data</h2>
        <p>Authentication is handled through Supabase and configured identity providers. When you use Google or Microsoft sign-in, Riseklix may receive basic account information such as your verified email, display name and profile image from that provider.</p>

        <h2>4. How information is used</h2>
        <p>We use information to authenticate users, operate organization workspaces, perform requested research, prevent abuse, measure usage, improve reliability, provide support and enforce product limits.</p>

        <h2>5. AI and infrastructure providers</h2>
        <p>When a project runs, relevant buyer questions and research context may be sent to the AI providers enabled for that workflow. Infrastructure providers may also process data necessary to host, secure and operate the service. We aim to send only the information needed for the requested operation.</p>

        <h2>6. Public versus private research</h2>
        <p>Company research may use publicly available web information. Private workspace information is not made public merely because it is stored in Riseklix. Users should avoid submitting sensitive information that is unnecessary for the analysis.</p>

        <h2>7. Security and abuse prevention</h2>
        <p>We use authenticated workspaces, row-level access controls, provider secrets kept server-side, CAPTCHA support, usage limits and audit records to reduce unauthorized access and automated abuse. No online service can guarantee absolute security.</p>

        <h2>8. Retention and deletion</h2>
        <p>Project and account information is retained while needed to provide the service, preserve longitudinal benchmarks, meet operational requirements or resolve disputes. Account and deletion controls will expand as the beta product matures.</p>

        <h2>9. Changes</h2>
        <p>We may update this policy as Riseklix adds billing, connected applications, expert delivery or other product capabilities. Material changes will be reflected in the published policy.</p>

        <h2>10. Contact</h2>
        <p>Privacy questions can be sent through the support contact published in the Riseklix application or website.</p>

        <footer><Link href="/terms">Terms of Service</Link><Link href="/login">Back to sign in</Link></footer>
      </article>
    </main>
  )
}
